[package]
name = "zeth-testeth"
version = "0.1.0"
edition = "2021"

[features]
ef-tests = []

[dependencies]
anyhow = "1.0"
ethers-core = { version = "2.0", features = ["optimism"] }
hashbrown = { version = "0.13", features = ["inline-more"] }
revm = { version = "3.3", default-features = false, features = ["std", "serde"] }
serde = "1.0"
serde_json = "1.0"
serde_with = "3.1"
stacker = "0.1"
zeth-guests = { path = "../../guests" }
zeth-lib = { path = "../../lib" }
zeth-primitives = { path = "../../primitives" }

[dev-dependencies]
env_logger = "0.10"
log = "0.4"
risc0-zkvm = { workspace = true, features = ["prove"] }
rstest = "0.18"
tempfile = "3.6"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["testguest"]
