[package]
name = "zeth-testeth"
version = "0.1.0"
edition = "2021"

[features]
ef-tests = []

[dependencies]
anyhow = { version = "1.0", default-features = false }
ethers-core = { version = "2.0", features = ["optimism"] }
hashbrown = { workspace = true }
revm = { workspace = true }
serde = "1.0"
serde_json = "1.0"
serde_with = "3.1"
zeth-lib = { path = "../../lib" }
zeth-primitives = { path = "../../primitives" }
host_util = { path = "../../host" }

[dev-dependencies]
diff = "0.1"
env_logger = "0.10"
log = "0.4"
risc0-zkvm = { workspace = true, features = ["prove"] }
rstest = "0.18"
tempfile = "3.6"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["testguest"]
