[package]
name = "test-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.1-rc.0", default-features = false, features = [ "std", "unstable" ] }
zeth-lib = { path = "../../../lib", default-features = false }

[patch.crates-io]
# use optimized risc0 circuit
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.1" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", rev = "33920ca9ce7060c2b88002356fea34f309a0517a" }
