[package]
name = "zeth-optimism"
version = "0.1.0"
edition = "2021"

[dependencies.zeth]
workspace = true

[dependencies.zeth-preflight-optimism]
workspace = true

[dependencies.zeth-guests]
workspace = true


[dependencies]
anyhow.workspace = true
reth-chainspec.workspace = true
tokio.workspace = true

[features]
debug-guest-build = ["zeth-guests/debug-guest-build"]
disable-dev-mode = ["zeth/disable-dev-mode"]
cuda = ["zeth/cuda"]
metal = ["zeth/metal"]
prove = ["zeth/prove"]
erigon-range-queries = ["zeth-preflight-optimism/erigon-range-queries"]
